AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Reboot_EC2-AUS

  Sample SAM Template for Reboot_EC2-AUS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  reboot_ec2_auFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: reboot_ec2_aus/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        reboot_ec2_au:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /reboot_ec2_au
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  reboot_ec2_auApi:
    Description: "API Gateway endpoint URL for Prod stage for reboot_ec2_au function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/reboot_ec2_au/"
  reboot_ec2_auFunction:
    Description: "reboot_ec2_au Lambda Function ARN"
    Value: !GetAtt reboot_ec2_auFunction.Arn
  reboot_ec2_auFunctionIamRole:
    Description: "Implicit IAM Role created for reboot_ec2_au function"
    Value: !GetAtt reboot_ec2_auFunctionRole.Arn
